[tool.poetry]
authors = ["A. Taqi"]
description = "Zernike polynomials"
license = "BSD-3-Clause"
name = "zernike"
readme = "README.md"
repository = "https://github.com/alitaqiEngOx/zernike"
version = "0.1.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry.scripts]
zernike-convert = "zernike.apps.convert:main"
zernike-estimate = "zernike.apps.estimate_beam:main"
zernike-extract = "zernike.apps.kernel_from_npz:main"
zernike-plot = "zernike.apps.plot_aberration:main"

[tool.poetry.dependencies]
matplotlib = "^3.9.2"
numpy = "^2.1.2"
python = ">=3.11, <3.13"
PyYAML = "^6.0.2"
scipy = "^1.14.1"
